### ISSUE TITLE
CLI Tests

### ISSUE THREAD

**Issue by triceam** [IBM-Cloud/ibm-developer-extension-vscode#7]
Need tests/tasks for the extension/CLI to detect/mitigate changes in the CLI that will break the VS Code extension. Could be based on metadata to check that specific cli commands are still available.

Possibilities:

- gulp tasks that are run to detect breaking changes
- run when the vs code extension is built
- run when code/PR is merged
- fun from cli builds

**Comment by Aerex** [comment]
Resolved in another repo
